sudo: false

language: php

# Run on PHP 7.2 and newer
php:
  - 7.2
  - nightly

# Cache yarn
cache:
  yarn: true
  directories:
    - $HOME/.composer
    - vendor/

before_install:
  # Install NodeJS
  - nvm install node
  - npm install -g yarn

install:
  # Download composer assets
  - composer install --no-progress --no-suggest -an

  # Download Yarn assets using lockfile
  - yarn install --frozen-lockfile

script:
  # Lint PHP code
  - vendor/bin/phpcs

  # Lint Sass files
  - find assets/ -type f -name '*.scss' -print | xargs node_modules/.bin/stylelint

  # Lint Javascript
  - find assets/ -type f -name '*.js' -print | xargs node_modules/.bin/eslint

  # Make zipfile
  - make gumbo-millennium.zip

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

deploy:
  provider: releases
  api_key:
    secure: dhMg351S8t4hrmg3T0XSn7ilQ444cxfFvetZVVK3h25w1PBL532sB7xOhWJN/JXcvF1eUN5C5kwUL7zxVuWbZCuDbNfVWFFUa6vnc6wPWbE+9ZDGiFNXohTZ/aRuMeSYesWKfdU+rgzwEYITNtaeNtLJvaj1tZxdlKB7zdUc+h20GNfj8WLcDk2T2GJF+3aYw5FZATYSExbs+tyUg+ULlSzgqszT6Z5DuGUXFWN/WS7dhIh1BnTMeIACZ/yB1yZJx6wU1KuvFHlYJ/8Kc2pwyWkgsC8cYzpaXVi0bi4JA5EfsHvqrT6tcqTZruBTEi5nTXccVtUl7omLSo0iZJofrwI8uFBMSkLWw5n7+UcZ69r6PgbO2sYKFDEKCNCdY3eF0tyBsxGioJ7YEzPJRNvq3oQkyS9qaQKl9hraKhktcsb1d6Z9+aysofdiHwv8jUx/CXxIYl9OtNpFtsFm5VD1OcXRVudMidHT547jNOrH2D/w1ZxR4F0FHnMhvurT/BRo4DfApUVm12kGopfPDCOkgKtpy5iG0DMOw5KgVGHULyzVHBpKeCkaaA8A8ir6RYldhJkXQE2qCpkTBiCeAopzbXo/kAb3hRkgtvKlrxOn+YWICKghFVmDeiufsk+UnQKpxO+ez6gbYlZR/mXkJ3XyHy5NhyHTC1AzwNmDRvkru5Y=
  file: "gumbo-millennium.zip"
  skip_cleanup: true
  on:
    tags: true
